export default [
  {
    shortName: 'orf1',
    name: 'ORF Eins',
    streamurl: 'http://apasfiisl.apa.at/ipad/orf1_q8c/orf.sdp/playlist.m3u8',
    website: 'http://orf.at',
    color: '#007787',
    dark: false,
    format: 'application/x-mpegURL',
  },
  {
    shortName: 'orf2',
    name: 'ORF 2',
    streamurl: 'http://apasfiisl.apa.at/ipad/orf2_q4a/orf.sdp/playlist.m3u8',
    color: '#e50020',
    dark: true,
    format: 'application/x-mpegURL',
  },
  {
    shortName: 'orf3',
    name: 'ORF III',
    streamurl: 'http://apasfiisl.apa.at/ipad/orf3_q4a/orf.sdp/playlist.m3u8',
    color: '#565656',
    dark: false,
    format: 'application/x-mpegURL',
  },
  {
    shortName: 'orfs',
    name: 'ORF Sport +',
    streamurl: 'http://apasfiisl.apa.at/ipad/orfs_q6a/orf.sdp/playlist.m3u8',
    color: '#236297',
    dark: false,
    format: 'application/x-mpegURL',
  },
  {
    shortName: 'servustv',
    name: 'Servus TV',
    streamurl: 'http://hdiosstv-f.akamaihd.net/i/servustvhd_1@51229/master.m3u8',
    color: '#f7f6f4',
    dark: true,
    format: 'application/x-mpegURL',
  },
  {
    shortName: '3sat',
    name: '3 SAT',
    streamurl: 'https://zdf0910-lh.akamaihd.net/i/dach10_v1@392872/master.m3u8',
    website: 'http://www.3sat.com',
    color: '#d2002e',
    dark: true,
    format: 'application/x-mpegURL',
  },
  {
    shortName: 'ard',
    name: 'ARD',
    streamurl: 'http://live-lh.daserste.de/i/daserste_de@91204/master.m3u8',
    website: 'http://www.ard.de',
    color: '#003771',
    dark: false,
    format: 'application/x-mpegURL',
  },
  {
    shortName: 'ntv',
    name: 'N-TV',
    streamurl: 'http://p.live.akamai.n-tv.de/playlists/ntvlive-ipadakamai.m3u8',
    website: 'http://www.n-tv.de',
    color: '#FF0000',
    dark: true,
    format: 'application/x-mpegURL',
  },
  {
    shortName: 'n24',
    name: 'N24',
    streamurl: 'https://live2weltcms-lh.akamaihd.net/i/Live2WeltCMS_1@444563/index_1_av-b.m3u8',
    website: 'http://www.n24.de',
    color: '#0000ff',
    dark: true,
    format: 'application/x-mpegURL',
  },
  {
    shortName: 'ndr',
    name: 'NDR',
    streamurl: 'http://ndr_fs-lh.akamaihd.net/i/ndrfs_nds@119224/master.m3u8',
    website: 'http://www.ndr.de',
    color: '#2366b9',
    dark: true,
    format: 'application/x-mpegURL',
  },
];
